apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-service
  labels:
    app: alert-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-service
  template:
    metadata:
      labels:
        app: alert-service
    spec:
      containers:
      - name: alert-service
        image: dddddddff/alert-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/risk_monitoring"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: alert-service
  labels:
    app: alert-service
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: alert-service
