apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: risk-monitoring
type: Opaque
stringData:
  # Database Credentials
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
  
  # RabbitMQ Credentials
  MQ_USERNAME: "guest"
  MQ_PASSWORD: "guest"
  
  # JWT Secret (change this in production!)
  JWT_SECRET: "change-this-to-a-secure-secret-in-production-key-12345"
